// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjbfuvkrvsluqzboyojk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqYmZ1dmtydnNsdXF6Ym95b2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTUyMDIsImV4cCI6MjA3Mzc5MTIwMn0.d7pqHtlQVz-1me8s54qXPC6Vf8oFoBdpJdX9Lupta9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});